#%RAML 0.8

title: World Music API
baseUri: http://example.api.com/
version: v1

/songs:
  get:
    queryParameters:
      genre:
        description: filter the song by genre
    responses:
      200:
        body:
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/schema",
                "type": "array",
                "items" : {
                  "type" : "object",
                  "description": "A canonical song",
                  "properties": {
                    "title": { "type": "string" },
                    "artist": { "type": "string"}
                  },
                  "required": [ "title", "artist" ]
                }
              }
  post:
  /{songId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "A canonical song",
                  "properties": {
                    "title": { "type": "string" },
                    "artist": { "type": "string"}
                  },
                  "required": [ "title", "artist" ]
                }
    delete:
      description: |
        This method will *delete* an **individual song**
